# Generated by Django 4.2.19 on 2026-02-17 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queries', '0002_saved_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('similar', 'Similar Query'), ('trending', 'Trending Query'), ('related', 'Related Query'), ('popular', 'Popular Query'), ('completion', 'Query Completion')], max_length=20)),
                ('query_text', models.TextField()),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('shown_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_shown_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('definition', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('step_results', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('failed_step', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['user', '-created_at'], name='queries_que_user_id_faf780_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['platform', '-created_at'], name='queries_que_platfor_a7c118_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['was_successful', '-created_at'], name='queries_que_was_suc_5ff0ae_idx'),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='queries.workflow'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querysuggestion',
            name='source_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='queries.querylog'),
        ),
        migrations.AddField(
            model_name='querysuggestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', '-started_at'], name='queries_wor_workflo_863796_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['user', '-started_at'], name='queries_wor_user_id_0afa95_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status'], name='queries_wor_status_36b991_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['user', 'status'], name='queries_wor_user_id_01cb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='querysuggestion',
            index=models.Index(fields=['user', '-confidence_score'], name='queries_que_user_id_63a9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='querysuggestion',
            index=models.Index(fields=['suggestion_type', '-confidence_score'], name='queries_que_suggest_f125d3_idx'),
        ),
        migrations.AddIndex(
            model_name='querysuggestion',
            index=models.Index(fields=['platform', '-confidence_score'], name='queries_que_platfor_58e539_idx'),
        ),
    ]
