# Generated by Django 6.0.1 on 2026-02-05 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolSpecMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_id', models.CharField(max_length=200, unique=True)),
                ('platform', models.CharField(db_index=True, max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('file_hash', models.CharField(max_length=64)),
                ('governance_class', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('MONEY_MOVE', 'Money Move')], default='READ', max_length=20)),
                ('semantic_description', models.TextField(blank=True)),
                ('embedding_id', models.CharField(blank=True, max_length=100, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tool_spec_metadata',
                'ordering': ['platform', 'tool_id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessGlossary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(db_index=True, max_length=200)),
                ('canonical_term', models.CharField(max_length=200)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_exact_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business Glossary',
                'db_table': 'business_glossary',
                'ordering': ['term'],
                'unique_together': {('user', 'term', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='PlatformOntology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(db_index=True, max_length=50)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('canonical_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.platformontology')),
            ],
            options={
                'verbose_name_plural': 'Platform Ontologies',
                'db_table': 'platform_ontology',
                'ordering': ['platform', 'entity_type'],
                'unique_together': {('platform', 'entity_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TenantCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(db_index=True, max_length=50)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('external_id', models.CharField(db_index=True, max_length=200)),
                ('display_name', models.CharField(max_length=500)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_catalog',
                'ordering': ['platform', 'entity_type', 'display_name'],
                'indexes': [models.Index(fields=['user', 'platform'], name='tenant_cata_user_id_230c4e_idx'), models.Index(fields=['platform', 'entity_type'], name='tenant_cata_platfor_694cd9_idx'), models.Index(fields=['external_id'], name='tenant_cata_externa_722e14_idx')],
            },
        ),
    ]
