# Generated by Django 6.0.1 on 2026-01-14 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('stripe', 'Stripe'), ('zendesk', 'Zendesk')], max_length=20)),
                ('encrypted_api_key', models.TextField()),
                ('is_valid', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
