# Generated by Django 6.0.1 on 2026-01-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='platform',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('zendesk', 'Zendesk'), ('github', 'GitHub')], max_length=20),
        ),
    ]
