# Generated by Django 6.0.1 on 2026-02-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_alter_platformconnection_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='platform',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('zoho', 'Zoho CRM'), ('github', 'GitHub'), ('trello', 'Trello'), ('salesforce', 'Salesforce')], max_length=20),
        ),
    ]
